const catppuccin = {
    latte: {
        base: '#eff1f5',
        mantle: '#e6e9ef',
        crust: '#dce0e8',
        text: '#4c4f69',
        subtext1: '#5c5f77',
        subtext0: '#6c6f85',
        surface0: '#ccd0da',
        surface1: '#bcc0cc',
        surface2: '#acb0be',
        overlay0: '#9ca0b0',
        overlay1: '#8c8fa1',
        overlay2: '#7c7f93',
        blue: '#1e66f5',
        lavender: '#7287fd',
        red: '#d20f39',
        green: '#40a02b',
        yellow: '#df8e1d',
        peach: '#fe640b',
        pink: '#ea76cb',
        teal: '#179299',
        mauve: '#8839ef',
    },
    mocha: {
        base: '#1e1e2e',
        mantle: '#181825',
        crust: '#11111b',
        text: '#cdd6f4',
        subtext1: '#bac2de',
        subtext0: '#a6adc8',
        surface0: '#313244',
        surface1: '#45475a',
        surface2: '#585b70',
        overlay0: '#6c7086',
        overlay1: '#7f849c',
        overlay2: '#9399b2',
        blue: '#89b4fa',
        lavender: '#b4befe',
        red: '#f38ba8',
        green: '#a6e3a1',
        yellow: '#f9e2af',
        peach: '#fab387',
        pink: '#f5c2e7',
        teal: '#94e2d5',
        mauve: '#cba6f7',
    },
};

export const lightTheme = {
    mode: 'light',
    background: catppuccin.latte.base,
    foreground: catppuccin.latte.text,
    primary: catppuccin.latte.blue,
    secondary: catppuccin.latte.green,
    accent: catppuccin.latte.mauve,
    danger: catppuccin.latte.red,
    warning: catppuccin.latte.yellow,
    success: catppuccin.latte.green,
    border: catppuccin.latte.surface1,
    surface: catppuccin.latte.surface0,
    muted: catppuccin.latte.subtext1,
    colors: catppuccin.latte,
};

export const darkTheme = {
    mode: 'dark',
    background: catppuccin.mocha.base,
    foreground: catppuccin.mocha.text,
    primary: catppuccin.mocha.blue,
    secondary: catppuccin.mocha.green,
    accent: catppuccin.mocha.mauve,
    danger: catppuccin.mocha.red,
    warning: catppuccin.mocha.yellow,
    success: catppuccin.mocha.green,
    border: catppuccin.mocha.surface1,
    surface: catppuccin.mocha.surface0,
    muted: catppuccin.mocha.subtext1,
    colors: catppuccin.mocha,
};
